use crate::prng::{ get_time_seed, PRNG };

// See https://en.wikipedia.org/wiki/Mersenne_Twister
// This is a 64-bit implementation and uses the 64-bit MT parameters.
// NOTE: This implementation does use magic numbers!! While some of these
// could potentially be constants, there are not meaningful names that can
// necessarily be applied to every constant value in the implementation.

/// Size of internal Mersenne Twister state table
const STATE_TABLE_LENGTH: usize = 312;

/// Mask off the lower portion of a 64 bit unsigned integer
/// When applied will give the lower bits in a 64-bit uint.
const LOWER_MASK: u64 = (1 << 31) - 1;

/// Mask off the upper portion of a 64 bit unsigned integer.
/// When applied will give the upper bits in a 64-bit uint.
const UPPER_MASK: u64 = !(LOWER_MASK) - 1;

/// Mersenne-Twister pseudo-random number generator internal state
#[derive(Debug)]
pub struct MersenneTwister {
    /// Internal state table for the Mersenne Twister calculations
    mt_table: [u64; STATE_TABLE_LENGTH],

    /// Current index into the Mersenne Twister state table
    index: usize
}

/// Mersenne Twister method implementations
impl MersenneTwister {
    /// Perform `twist` shuffle of internal Mersenne Twister state table.
    fn twist(&mut self) {
        // Shuffle the Mersenne Twister state table
        for i in 0..STATE_TABLE_LENGTH {
            let x = (self.mt_table[i] & UPPER_MASK) | (self.mt_table[(i + 1) % STATE_TABLE_LENGTH] & LOWER_MASK);
            let mut xshft = x >> 1;
            if xshft % 2 != 0 {
                xshft ^= 0xB5026F5AA96619E9;
            }
            self.mt_table[i] = self.mt_table[(i + 156) % STATE_TABLE_LENGTH] ^ xshft;
        }

        // Reset the index into the state table to the beginning
        self.index = 0;
    }
}

/// Mersenne Twister implementation for the pseudo-random number generator trait
impl PRNG for MersenneTwister {
    /// Instantiate a new Mersenne Twister 64-bit pseudo-random number generator with the current time.
    fn new() -> Self {
        let mut table: [u64; STATE_TABLE_LENGTH] = [0; STATE_TABLE_LENGTH];
        table[0] = get_time_seed(); // Set the first element of our table to use current time as seed
        for i in 1..STATE_TABLE_LENGTH {
            let prev = table[i-1];
            let factor = (6364136223846793005 * ((prev ^ (prev >> 29)) + (i as u64)) as u128) as u64;
            table[i] = (factor & LOWER_MASK) as u64;
        }

        MersenneTwister{
            mt_table: table,
            index: STATE_TABLE_LENGTH
        }
    }

    /// Calculate the next number generated by the pseudo-random number generator.
    fn next(&mut self) -> u64 {
        if self.index >= STATE_TABLE_LENGTH {
            self.twist();
        }

        // These constants come from the Wikipedia link at the top of the page.
        let mut y = self.mt_table[self.index];
        y ^= (y >> 29) & 0x5555555555555555;
        y ^= (y << 17) & 0x71D67FFFEDA60000;
        y ^= (y << 37) & 0xFFF7EEE000000000;
        y ^= y >> 43;

        self.index += 1;
        y & LOWER_MASK
    }
}
